
CONTAINER_NAME=$1
IP=$2
PANEL_PORT=$3
VERIFIER_PORT=$4
LOGO=$5
TITLE=$6
MAIN_COLOR=$7
SECONDARY_COLOR=$8
CRED_TYPE_FILE=$9
SESSION_NAME=${10}
ANONYMOUS=${11}
ADMIN_USER=${12}
ADMIN_PASS=${13}
MASTER_NODE_URL=${14}

if [[ -z "$ADMIN_USER" ]]; then
  ADMIN_USER="admin"
fi

if [[ -z "$ADMIN_PASS" ]]; then
  ADMIN_PASS="yotiadmin"
fi

docker run -d --name $CONTAINER_NAME \
  -p $PANEL_PORT:$PANEL_PORT \
  -p $VERIFIER_PORT:$VERIFIER_PORT \
  -e IP=$IP \
  -e VERIFIER_PANEL_PORT=$PANEL_PORT \
  -e VERIFIER_IP=$IP \
  -e VERIFIER_PORT=$VERIFIER_PORT \
  -e VERIFIER_PANEL_IP_ADDRESS="https://$IP:$PANEL_PORT/" \
  -e VERIFIER_PORT=$VERIFIER_PORT \
  -e REACT_APP_VERIFIER_PANEL_LOGO="$LOGO" \
  -e REACT_APP_VERIFIER_PANEL_COLOR="$MAIN_COLOR" \
  -e REACT_APP_VERIFIER_PANEL_SECONDARY_COLOR="$SECONDARY_COLOR" \
  -e REACT_APP_VERIFIER_PANEL_TITLE="$TITLE" \
  -e CRED_TYPE_PATH="../idemix_files/$CRED_TYPE_FILE" \
  -e SESSION_NAME="$SESSION_NAME" \
  -e REACT_APP_ANONYMOUS="$ANONYMOUS" \
  -e ADMIN_USER=$ADMIN_USER \
  -e ADMIN_PASS=$ADMIN_PASS \
  -e MASTER_NODE_URL="$MASTER_NODE_URL" \
  -e VERIFIER_FULL_URL="http://$IP:$VERIFIER_PORT/" \
  eu.gcr.io/yoti-blockchain/verifier_panel