CONTAINER_NAME=$1
IP=$2
PANEL_PORT=$3
ISSUER_PORT=$4
LOGO=$5
TITLE=$6
MAIN_COLOR=$7
SECONDARY_COLOR=$8
CRED_TYPE_FILE=$9
ISSUER_IP=${10}
SESSION_NAME=${11}
ISSUER_TYPE=${12}

ADMIN_USER=${13}
ADMIN_PASS=${14}

MASTER_NODE_URL=${15}

if [[ -z "$ADMIN_USER" ]]; then
  ADMIN_USER="admin"
fi

if [[ -z "$ADMIN_PASS" ]]; then
  ADMIN_PASS="yotiadmin"
fi

docker run -d --name $CONTAINER_NAME \
  -p $PANEL_PORT:$PANEL_PORT \
  -p $ISSUER_PORT:$ISSUER_PORT \
  -e IP=$IP \
  -e ISSUER_PANEL_IP_ADDRESS="https://$IP:$PANEL_PORT/" \
  -e ISSUER_PANEL_PORT=$PANEL_PORT \
  -e ISSUER_PORT=$ISSUER_PORT \
  -e ISSUER_DID_PATH="../idemix_files/$ISSUER_DID_FILE" \
  -e REACT_APP_ISSUER_PANEL_LOGO="$LOGO" \
  -e REACT_APP_ISSUER_PANEL_TITLE="$TITLE" \
  -e REACT_APP_ISSUER_PANEL_COLOR="$MAIN_COLOR" \
  -e REACT_APP_ISSUER_PANEL_SECONDARY_COLOR="$SECONDARY_COLOR" \
  -e CRED_TYPE_PATH="../idemix_files/$CRED_TYPE_FILE" \
  -e ISSUER_IP=$ISSUER_IP \
  -e SESSION_NAME=$SESSION_NAME \
  -e YOTI_PEM_FILE_PATH="./deployment_files/$YOTI_PEM_FILE" \
  -e YOTI_SDK_ID="$YOTI_SDK_ID" \
  -e REACT_APP_YOTI_APP_ID="$REACT_APP_YOTI_APP_ID" \
  -e ADMIN_USER=$ADMIN_USER \
  -e ADMIN_PASS=$ADMIN_PASS \
  -e REACT_APP_PANEL_TYPE=$ISSUER_TYPE \
  -e MASTER_NODE_URL="$MASTER_NODE_URL" \
  -e ISSUER_FULL_URL="http://$IP:$ISSUER_PORT/" \
  eu.gcr.io/yoti-blockchain/issuer_panel